// decision-tech-react-seed/src/components/app/app.jsx
import React from 'react';
import './app.scss';
import dealData from '../../assets/deals.json';
import SiteNav from '../site-nav/site-nav';
import DealTable from '../deal-table/deal-table';
import DealFilter from '../deal-filter/deal-filter';

class App extends React.Component {
  constructor() {
    super();

    this.state = {
      filter: {
        broadband: false,
        tv: false,
        mobile: false
      },
      data: dealData.deals
    };
  }

  handleFilterChange(event) {
    console.log(event);
  }

  render() {
    return (
      <div className="app">
        <SiteNav />
        <div className="deals-layout">
          <DealFilter handleChange={this.handleFilterChange} />
          <div className="deals-layout__grid">
            <DealTable deals={this.state.data} />
          </div>
        </div>
      </div>
    );
  }
}

export default App;

// decision-tech-vue-seed/src/Components/app/app.vue
<template>
    <div class="deals-layout">
        <DealFilter/>
        <div class="deals-layout__grid">
            <DealTable :deals="deals" />
        </div>
    </div>
</template>

<script>
import DealFilter from '../deal-filter/deal-filter.vue';
import DealTable from '../deal-table/deal-table.vue';
import data from '../../assets/deals.json';

export default {
    data: function () {
        return {
            deals: data.deals
        }
    },
    components: { DealFilter, DealTable }
}
</script>

<style lang="scss">
.deals-layout {
    display: flex;
    height: 100%;
    max-width: 1260px;
    margin: 0 auto;
    width: 100%;
    
    &__grid {
        flex: 1;
    }
}
</style>
