// decision-tech-react-seed/src/Components/dealfilter/dealfilter-component.jsx
import React from 'react';
import './dealfilter.scss';
class SpeedFilter extends React.Component {
    render() {
        if (this.props.filterState.productTypes.broadband) {
            return (<div>
                <div>Speed</div>
                <select value={this.props.filterState.speed} onChange={this.props.filterChanged}>
                    <option value="">Any</option>
                    <option value="17408">17MB</option>
                    <option value="53248">52MB</option>
                    <option value="77824">76MB</option>
                </select></div>)
        } else return (null)
    }
}

class MobileFilter extends React.Component {
    render() {
        if (this.props.filterState.productTypes.mobile)
            return (
                <div>
                    <div>Mobile Data</div>
                    <select value={this.props.filterState.mobileData} onChange={thihs.props.filterChanged}>
                        <option value="">Any</option>
                        <option value="2">2GB</option>
                        <option value="5">5GB</option>
                    </select>
                </div>
            )
        else return (null)
    }
}


export class DealFilter extends React.Component {
    render() {
        return (<div className={`deal-filter-menu`}>
            <ul>
                <li><input type="checkbox" disabled checked={this.props.filterState.productTypes.broadband} onChange={this.props.filterChanged} /> Broadband</li>
                <li><input type="checkbox" checked={this.props.filterState.productTypes.tv} onChange={this.props.filterChanged} /> TV</li>
                <li><input type="checkbox" checked={this.props.filterState.productTypes.mobile} onChange={this.props.filterChanged} /> Mo</li>
            </ul>
            <SpeedFilter filterState={this.props.filterState} filterChanged={this.props.filterChanged} />
            <MobileFilter filterState={this.props.filterState} filterChanged={this.props.filterChanged} />
        </div>);
    }
}

// decision-tech-vue-seed/src/Components/deal-filter/deal-filter.vue
<template>
    <div class="filter-menu">
        <ul>
            <li>
                <input id="filter-broadband" type="checkbox" v-model="filter.broadband" @change="filterChanged" value="broadband" />
                <label for="filter-broadband">Broadband</label>
            </li>
            <li>
                <input id="filter-tv" type="checkbox" v-model="filter.tv" @change="filterChanged" value="tv" />
                <label for="filter-tv">TV</label>
            </li>
            <li>
                <input id="filter-mobile" type="checkbox" v-model="filter.mobile" @change="filterChanged" value="mobile" />
                <label for="filter-mobile">Mobile</label>
            </li>
        </ul>
    </div>
</template>

<script>
export default {
    data: function () {
        return {
            filter: {
                broadband: false,
                tv: false,
                mobile: false
            }
        };
    },
    methods: {
        filterChanged(event) {
            console.log(event);
        }
    }
}
</script>

<style lang="scss">
.filter-menu {
    width: 200px;
    padding: 0 8px;
    background-color: #dedede;
    height: 100%;
}
</style>
