// decision-tech-angular-seed/src/app/app.component.ts
import { Component } from '@angular/core';
import { Http } from '@angular/http';
import 'rxjs/add/operator/map';
import { BroadbandResult } from "app/types/broadbanddeals";
import { FilterStateService } from "app/services/filterStateService";
import { Subscription } from "rxjs/Subscription";
import { FilterState } from "app/services/filterState";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  private subscription: Subscription;
  constructor(http: Http, private _filterStateService: FilterStateService) {
    http.get('assets/deals.json')
      .map(res => res.json())
      .subscribe(result => this.deals = result.deals);
    this.subscription = this._filterStateService.getState()
      .subscribe(state => console.log(state));
  }

  title = "start"
  deals: BroadbandResult.Deal[] = []

  ngOnDestroy() {
    this.subscription.unsubscribe();
  }
}

<site-nav></site-nav>
<div class="deals-layout">
    <filter-bar></filter-bar>
    <broadband-grid [deals]="deals" class="deals-layout__grid"></broadband-grid>
</div>

// decision-tech-react-seed/src/components/app/app.jsx
import React from 'react';
import './app.scss';
import dealData from '../../assets/deals.json';
import SiteNav from '../site-nav/site-nav';
import DealTable from '../deal-table/deal-table'
import DealFilter from '../deal-filter/deal-filter';

class App extends React.Component {
  constructor() {
    super();

    this.state = {
      filter: {
        broadband: false,
        tv: false,
        mobile: false
      },
      data: dealData.deals
    };
  }

  handleFilterChange(event) {
    console.log(event);
  }

  render() {
    return (
      <div className="app">
        <SiteNav></SiteNav>
        <div className="deals-layout">
          <DealFilter filterState={this.state.filter} handleChange={this.handleFilterChange} />
          <div className="deals-layout__grid">
            <DealTable deals={this.state.data} />
          </div>
        </div>
      </div>
    );
  }
}

export default App;
